development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  host: localhost
  pool: 5
